# Generated by Django 4.2.3 on 2023-07-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(default=0, null=True)),
                ('address', models.TextField(max_length=300)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='buyer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('formal', 'formal'), ('stports', 'sports'), ('casual', 'casual')], max_length=100)),
                ('product_brand', models.CharField(choices=[('puma', 'puma'), ('Rebook', 'Rebook'), ('Adidas', 'Adidas'), ('calcetto', 'calcetto'), ('Bata', 'Bata')], max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_size', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=100)),
                ('product_pic', models.ImageField(default='', upload_to='product_pic')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
